apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: strimzipodset-rule
  namespace: monitoring
spec:
  groups:
   - name: k8s.rules
     rules:
     - expr: |
         max by (cluster, namespace, workload, pod) (
           label_replace(
             kube_pod_owner{job="kube-state-metrics", owner_kind="StrimziPodSet"},
             "workload", "$1", "owner_name", "(.*)"
           )
         )
       labels:
         workload_type: strimzipodset
       record: namespace_workload_pod:kube_pod_owner:relabel
